version: '3'

services:
  postgres-docker:
    image: postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432